services:
  - type: web
    name: tunesmith-ai
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_SPOTIFY_CLIENT_ID
        sync: false
      - key: VITE_API_URL
        value: https://tunesmith-ai-api.onrender.com
      - key: VITE_SPOTIFY_REDIRECT_URI
        value: https://tunesmith-ai.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: tunesmith-ai-api
    env: deno
    buildCommand: deno cache supabase/functions/spotify-auth/index.ts
    startCommand: deno run --allow-net --allow-env supabase/functions/spotify-auth/index.ts
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://tunesmith-ai.onrender.com 
