
services:
  - type: web
    name: tunesmith-ai-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_SPOTIFY_CLIENT_ID
        sync: false
      - key: VITE_API_URL
        value: https://tunesmith-ai-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: tunesmith-ai-api
    env: node
    runtime: node
    buildCommand: cd supabase/functions/spotify-auth && npm install
    startCommand: cd supabase/functions/spotify-auth && node index.js
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: PORT
        value: 10000
